### ISSUE TITLE
4.8.0 release checklist

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#198]
- [x] Review open PRs
  - [x] merge #192 (needs conflict fixes)
  - [x] merge #196 
  - [x] merge #197
  - [x] merge #199 
  - [x] merge #200
  - [x] merge #202
  - [x] merge #203 
  - [x] Following #194, would be nice to remove `nose` references altogether
- [x] Review open issues for anything else that should go into this release. Possible candidates:
   - [x] #193 (remove update checker plugin)
   - [x] #163 (fix etstool to work with non-EDM environments on Windows)
   - [x] #174 (remove non-functional RefreshCodePlugin)
- [x] Update changelog
- [x] Make release branch
- [x] Bump version on release branch (via PR against release branch)
- [x] Bump version on master for continued development
- [x] Testing! (Create sdist, install from sdist, check tests pass.)
- [x] Tag
- [x] Testing!
- [x] Update release information on GitHub
- [x] PyPI upload
- [x] More testing!
- [x] Build and upload documentation.
- [x] Buildsystem issue for package update (https://github.com/enthought/buildsystem/issues/2572)
- [x] Bring any necessary changes back into master

---

After eggs are built for EDM:

- [x] One more round of testing with the EDM eggs
- [x] Announce the release (Slack, portal, ets-users)

**Comment by mdickinson** [comment]
All done. Closing.
