### ISSUE TITLE
4.9.0 release checklist

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#239]
- [x] Review open PRs
- [x] Review open issues for anything else that should go into this release.
- [x] Update changelog
- [x] Bump version on master for continued development (no need this time around)
- [x] Make release branch from master commit immediately preceding the version bump
- [x] Bump version on release branch (#241)
- [x] Test sdist! (Create sdist, install from sdist, check tests pass.)
- [x] Tag
- [x] Update release information on GitHub
- [x] PyPI upload
- [x] More testing!
- [x] Build and upload documentation.
- [x] Buildsystem issue for package update (internal buildsystem issue: enthought/buildsystem#2734)
- [x] Bring any necessary changes back into master (nothing to do this time around)

---

After eggs are built for EDM:

- [x] One more round of testing with the EDM eggs
- [x] Announce the release (Slack, portal, ets-users)

**Comment by mdickinson** [comment]
All done. Closing.
