### ISSUE TITLE
4.9.1 release checklist

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#257]
4.9.1 is a bugfix release primarily aimed at ensuring compatibility with the upcoming Traits 6.0.0 release.

- [x] Review open PRs
- [x] Review open issues for anything else that should go into this release.
- [x] If it doesn't already exist, or has been deleted, re-create the release branch `release/4.9.x` from the 4.9.0 tag.
- [x] Backport relevant PRs from the master branch. (New branch `pr-backports` created from the release branch.) Include changelog updates in this PR. (Pending: #258)
- [x] Update changelog. (Done in #258)
- [x] Bump version on release branch. (Pending: #259)
- [x] Test sdist! (Create sdist, install from sdist, check tests pass.)
- [x] Tag
- [x] Update release information on GitHub
- [x] PyPI upload
- [x] More testing!
- [x] Build, upload, and check documentation. (Pending: #261)
- [x] Buildsystem issue for package update (enthought/buildsystem#2943)
- [x] Bring any necessary changes back into master

---

After eggs are built for EDM:

- [x] One more round of testing with the EDM eggs
- [x] Announce the release (Slack, portal, ets-users)

**Comment by mdickinson** [comment]
PRs in master since the 4.9.0 release: #255, #253, #252, #250, #248, #243, #225.

Of those, #255, #253 and #250 can be regarded as compatibility bugfixes. I think we can sneak #252 in under the heading bugfix, too.

**Comment by mdickinson** [comment]
All done. Closing.

Note that there was also an emergency 4.9.2 release to fix two Category-related test failures with Traits 6.0. We haven't rebuilt the documentation for that release, since nothing will have changed in the docs.
