### ISSUE TITLE
5.0.0 release checklist

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#363]
Checklist based on release checklist for version 4.9.0 - https://github.com/enthought/envisage/issues/239

- [ ] Review open PRs (#357 ?)
- [ ] Review open issues for anything else that should go into this release.
- [ ] Update changelog (#364 )
- [ ] Bump version on master for continued development (#365)
- [ ] Make release branch from master commit immediately preceding the version bump
- [ ] Bump version on release branch
- [ ] Test sdist! (Create sdist, install from sdist, check tests pass.)
- [ ] Tag
- [ ] Update release information on GitHub
- [ ] PyPI upload
- [ ] More testing!
- [ ] Build and upload documentation.
- [ ] Buildsystem issue for package update
- [ ] Bring any necessary changes back into master

---

After eggs are built for EDM:

- [ ] One more round of testing with the EDM eggs
- [ ] Announce the release (Slack, portal, ets-users)

**Comment by aaronayres35** [comment]
ref: https://github.com/enthought/traitsui/issues/1307, https://github.com/enthought/pyface/issues/714

**Comment by aaronayres35** [comment]
closing as this is now superseded by #373
