### ISSUE TITLE
Broken links in tasks docs

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#71]
Broken links
- [x] [Footnote #1 in layout](http://docs.enthought.com/envisage/tasks_user_manual/layout.html#id4)
- [x] [Footnote #3 in layout](http://docs.enthought.com/envisage/tasks_user_manual/layout.html#id6)
- [x] [Footnote #2 in menus](http://docs.enthought.com/envisage/tasks_user_manual/menus.html#id2)
- [x] [Footnote #1 in extensibility](http://docs.enthought.com/envisage/tasks_user_manual/extensibility.html#id7)
- [x] [Footnote #2 in extensibility](http://docs.enthought.com/envisage/tasks_user_manual/extensibility.html#id8)
